# Generated by Django 4.0.5 on 2022-07-08 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TiendaActividades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actividad', models.CharField(max_length=30, verbose_name='Actividad')),
                ('profesor', models.CharField(max_length=30, verbose_name='NombreProfesor')),
                ('dias', models.CharField(max_length=30, verbose_name='Dias')),
                ('turno', models.PositiveSmallIntegerField(choices=[(1, 'mañana'), (1, 'tarde'), (1, 'noche')], verbose_name='Turno')),
                ('precio', models.FloatField(verbose_name='Precio $')),
            ],
        ),
    ]
