# Generated by Django 4.0.5 on 2022-07-09 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfilesapp', '0002_nosotros_profesores_socios_tiendaobjetos_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profesores',
            name='especialidad',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Clase individual'), (2, 'Clase grupal')], verbose_name='Especialidad'),
        ),
        migrations.AlterField(
            model_name='tiendaactividades',
            name='actividad',
            field=models.SmallIntegerField(choices=[(1, 'Curso individual'), (2, 'Curso para dos'), (3, 'Curso para cuatro'), (4, 'Salida en trainera')], verbose_name='Actividad'),
        ),
        migrations.AlterField(
            model_name='tiendaactividades',
            name='turno',
            field=models.PositiveSmallIntegerField(choices=[(1, 'mañana'), (2, 'tarde')], verbose_name='Turno'),
        ),
    ]
