# Generated by Django 4.0.5 on 2022-07-10 00:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('perfilesapp', '0003_alter_profesores_especialidad_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profesores',
            name='especialidad',
        ),
        migrations.RemoveField(
            model_name='profesores',
            name='fechanacimientoprofesor',
        ),
        migrations.RemoveField(
            model_name='profesores',
            name='sexoprofesor',
        ),
    ]
