# Generated by Django 4.0.5 on 2022-07-10 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('perfilesapp', '0005_rename_profesores_profesor'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='nosotros',
            options={'verbose_name_plural': 'Nosotros'},
        ),
        migrations.AlterModelOptions(
            name='profesor',
            options={'verbose_name_plural': 'Profesores'},
        ),
        migrations.AlterModelOptions(
            name='socios',
            options={'verbose_name_plural': 'Socios'},
        ),
        migrations.AlterModelOptions(
            name='tiendaactividades',
            options={'verbose_name_plural': 'Tienda de Actividades'},
        ),
        migrations.AlterModelOptions(
            name='tiendaobjetos',
            options={'verbose_name_plural': 'Tienda de Objetos'},
        ),
    ]
