# Generated by Django 4.0.5 on 2022-07-12 00:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('perfilesapp', '0007_remove_socios_sexo'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TiendaActividades',
            new_name='TiendaActividad',
        ),
    ]
