# Generated by Django 4.0.5 on 2022-07-12 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfilesapp', '0008_rename_tiendaactividades_tiendaactividad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tiendaactividad',
            name='actividad',
            field=models.CharField(choices=[('Curso Individual', 'Curso individual'), ('Curso para dos', 'Curso para dos'), ('Curso para cuatro', 'Curso para cuatro'), ('Salida en trainera', 'Salida en trainera')], max_length=30, verbose_name='Actividad'),
        ),
        migrations.AlterField(
            model_name='tiendaactividad',
            name='turno',
            field=models.CharField(choices=[('mañana', 'mañana'), ('tarde', 'tarde')], max_length=30, verbose_name='Turno'),
        ),
    ]
