# Generated by Django 4.0.5 on 2022-07-20 23:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('perfilesapp', '0013_rename_imagen_avatar_foto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='avatar',
            old_name='foto',
            new_name='avatar',
        ),
    ]
