# Generated by Django 4.0.5 on 2022-07-20 23:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('perfilesapp', '0014_rename_foto_avatar_avatar'),
    ]

    operations = [
        migrations.RenameField(
            model_name='avatar',
            old_name='avatar',
            new_name='imagen',
        ),
    ]
