# Generated by Django 4.0.5 on 2022-07-21 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfilesapp', '0016_alter_avatar_imagen'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Titulo')),
                ('subtitle', models.CharField(max_length=30, verbose_name='Subtitulo')),
                ('texto', models.CharField(max_length=5000, verbose_name='Texto')),
                ('imagen', models.ImageField(upload_to='', verbose_name='Imagen')),
                ('autor', models.CharField(max_length=15, verbose_name='Autor')),
                ('fecha', models.CharField(max_length=15, verbose_name='Fecha')),
            ],
        ),
    ]
