# Generated by Django 4.0.5 on 2022-07-21 02:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('perfilesapp', '0017_blog'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='subtitle',
            new_name='subtitulo',
        ),
        migrations.RenameField(
            model_name='blog',
            old_name='title',
            new_name='titulo',
        ),
    ]
