# Generated by Django 4.0.5 on 2022-07-22 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfilesapp', '0019_alter_blog_imagen'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comentarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=15, verbose_name='nombre')),
                ('comentario', models.TextField(verbose_name='comentario')),
            ],
        ),
    ]
