# Generated by Django 4.0.5 on 2022-07-22 02:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('perfilesapp', '0020_comentarios'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Comentarios',
            new_name='Comentario',
        ),
    ]
