# Generated by Django 4.0.5 on 2022-07-22 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfilesapp', '0021_rename_comentarios_comentario'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Nosotros',
        ),
        migrations.AlterField(
            model_name='comentario',
            name='comentario',
            field=models.CharField(max_length=500, verbose_name='comentario'),
        ),
    ]
