# Generated by Django 4.0.5 on 2022-07-22 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfilesapp', '0022_delete_nosotros_alter_comentario_comentario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentario',
            name='comentario',
            field=models.CharField(max_length=500, verbose_name='Comentario'),
        ),
        migrations.AlterField(
            model_name='comentario',
            name='nombre',
            field=models.CharField(max_length=15, verbose_name='Nombre'),
        ),
    ]
