# Generated by Django 4.0.5 on 2022-07-24 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfilesapp', '0024_alter_comentario_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentario',
            name='nombre',
            field=models.CharField(max_length=15, verbose_name='Nombre'),
        ),
    ]
