# Generated by Django 4.0.5 on 2022-07-24 02:23

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('perfilesapp', '0025_alter_comentario_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentario',
            name='blog',
            field=models.ForeignKey(default=0.0016249823371485093, on_delete=django.db.models.deletion.CASCADE, to='perfilesapp.blog'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comentario',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
