# Generated by Django 4.0.5 on 2022-07-24 02:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('perfilesapp', '0026_comentario_blog_comentario_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comentario',
            name='blog',
        ),
    ]
