# Generated by Django 4.0.5 on 2022-07-24 02:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('perfilesapp', '0027_remove_comentario_blog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comentario',
            name='created',
        ),
    ]
