# Generated by Django 4.0.5 on 2022-07-24 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('perfilesapp', '0028_remove_comentario_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='autor',
        ),
    ]
