# Generated by Django 4.0.5 on 2022-07-25 18:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('perfilesapp', '0031_alter_blog_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentario',
            name='blog',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='perfilesapp.blog', verbose_name='Blog'),
        ),
    ]
